version: "2"

services:
  sonnen_api:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 sonosServer.py 
    volumes:
      - ./code:/code
    ports:
      - 5002:5002
    restart: always
